import React from "react";
import { FileText, Edit, Trash2, Send, DollarSign, Download, Copy } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface InvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
  cgst?: number;
  sgst?: number;
  igst?: number;
}

interface Invoice {
  invoiceId: string;
  clientName: string;
  clientAddress: string;
  invoiceDate: string;
  dueDate: string;
  projectName: string;
  items: InvoiceItem[];
  subtotal: number;
  cgstRate: number;
  sgstRate: number;
  igstRate: number;
  cgstAmount: number;
  sgstAmount: number;
  igstAmount: number;
  totalTax: number;
  totalAmount: number;
  status: "draft" | "sent" | "paid" | "overdue";
  notes: string;
  timestamp: number;
}

interface InvoiceCardProps {
  invoice: Invoice;
  onViewDetails: (invoice: Invoice) => void;
  onEdit: (invoice: Invoice) => void;
  onDelete: (invoiceId: string) => void;
  onSend: (invoiceId: string) => void;
  onMarkAsPaid: (invoiceId: string) => void;
  onDuplicate: (invoice: Invoice) => void;
}

const InvoiceCard: React.FC<InvoiceCardProps> = ({ invoice, onViewDetails, onEdit, onDelete, onSend, onMarkAsPaid, onDuplicate }) => {
  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString();
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    
    // Add Company Branding
    doc.setFontSize(20);
    doc.setTextColor(33, 150, 243); // Blue color
    doc.text("Construction Co. Ltd.", 14, 20);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("123 Construction Lane, City, Country", 14, 28);
    doc.text("Phone: +123-456-7890 | Email: invoices@constructionco.com", 14, 34);
    doc.text("GSTIN: 12ABCDE1234F1Z5", 14, 40);

    // Invoice Title and Details
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("INVOICE", 160, 20, { align: "right" });
    doc.setFontSize(12);
    doc.text(`Invoice #: ${invoice.invoiceId}`, 160, 30, { align: "right" });
    doc.text(`Date: ${formatDate(invoice.invoiceDate)}`, 160, 38, { align: "right" });
    doc.text(`Due Date: ${formatDate(invoice.dueDate)}`, 160, 46, { align: "right" });

    // Client Details
    doc.setFontSize(12);
    doc.text("Bill To:", 14, 60);
    doc.setFontSize(10);
    doc.text(invoice.clientName, 14, 68);
    doc.text(invoice.clientAddress, 14, 76);
    doc.text(`Project: ${invoice.projectName}`, 14, 84);

    // Items Table
    autoTable(doc, {
      startY: 94,
      head: [["Description", "Qty", "Unit Price", "CGST", "SGST", "IGST", "Total"]],
      body: invoice.items.map(item => [
        item.description,
        item.quantity,
        `$${item.unitPrice.toFixed(2)}`,
        item.cgst ? `$${item.cgst.toFixed(2)}` : "-",
        item.sgst ? `$${item.sgst.toFixed(2)}` : "-",
        item.igst ? `$${item.igst.toFixed(2)}` : "-",
        `$${item.total.toFixed(2)}`,
      ]),
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [33, 150, 243], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 20 },
        2: { cellWidth: 30 },
        3: { cellWidth: 20 },
        4: { cellWidth: 20 },
        5: { cellWidth: 20 },
        6: { cellWidth: 20 },
      },
    });

    // Summary
    const finalY = (doc as any).lastAutoTable.finalY || 94;
    doc.setFontSize(10);
    doc.text(`Subtotal: $${invoice.subtotal.toFixed(2)}`, 140, finalY + 10, { align: "right" });
    doc.text(`CGST (${invoice.cgstRate}%): $${invoice.cgstAmount.toFixed(2)}`, 140, finalY + 18, { align: "right" });
    doc.text(`SGST (${invoice.sgstRate}%): $${invoice.sgstAmount.toFixed(2)}`, 140, finalY + 26, { align: "right" });
    doc.text(`IGST (${invoice.igstRate}%): $${invoice.igstAmount.toFixed(2)}`, 140, finalY + 34, { align: "right" });
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Total Amount: $${invoice.totalAmount.toFixed(2)}`, 140, finalY + 42, { align: "right" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes || "N/A"}`, 14, finalY + 52);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Construction Co. Ltd. | All rights reserved.", 14, 280);

    doc.save(`invoice_${invoice.invoiceId}.pdf`);
  };

  return (
    <div className="relative bg-white rounded-xl shadow-lg p-4 sm:p-6 mb-4 transition-all hover:shadow-2xl border-l-4 border-indigo-500">
      <div className="flex justify-between items-start mb-2">
        <div>
          <h3 className="text-lg sm:text-xl font-bold text-gray-800">Invoice #{invoice.invoiceId}</h3>
          <p className="text-sm text-gray-500">{invoice.clientName} - {invoice.projectName}</p>
        </div>
        <div className={`text-sm font-semibold px-3 py-1 rounded-full ${invoice.status === "paid" ? "bg-green-100 text-green-800" : invoice.status === "overdue" ? "bg-red-100 text-red-800" : invoice.status === "sent" ? "bg-blue-100 text-blue-800" : "bg-yellow-100 text-yellow-800"}`}>
          {invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}
        </div>
      </div>
      <div className="mt-2 space-y-1">
        <p className="text-sm text-gray-600"><strong>Total:</strong> ${invoice.totalAmount.toFixed(2)}</p>
        <p className="text-sm text-gray-600"><strong>Due Date:</strong> {formatDate(invoice.dueDate)}</p>
      </div>
      <div className="flex flex-wrap gap-2 mt-4">
        <button
          onClick={() => onViewDetails(invoice)}
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-indigo-500 text-white hover:bg-indigo-600 shadow-sm"
        >
          <FileText className="h-4 w-4" />
          View Details
        </button>
        {invoice.status === "draft" && (
          <>
            <button
              onClick={() => onEdit(invoice)}
              className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-yellow-500 text-white hover:bg-yellow-600 shadow-sm"
            >
              <Edit className="h-4 w-4" />
              Edit
            </button>
            <button
              onClick={() => onSend(invoice.invoiceId)}
              className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-blue-500 text-white hover:bg-blue-600 shadow-sm"
            >
              <Send className="h-4 w-4" />
              Send
            </button>
          </>
        )}
        {invoice.status === "sent" && (
          <button
            onClick={() => onMarkAsPaid(invoice.invoiceId)}
            className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-green-500 text-white hover:bg-green-600 shadow-sm"
          >
            <DollarSign className="h-4 w-4" />
            Mark as Paid
          </button>
        )}
        <button
          onClick={() => onDuplicate(invoice)}
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-purple-500 text-white hover:bg-purple-600 shadow-sm"
        >
          <Copy className="h-4 w-4" />
          Duplicate
        </button>
        <button
          onClick={() => onDelete(invoice.invoiceId)}
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-red-500 text-white hover:bg-red-600 shadow-sm"
        >
          <Trash2 className="h-4 w-4" />
          Delete
        </button>
        <button
          onClick={exportToPDF}
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-xs sm:text-sm font-medium transition-colors h-9 px-3 py-2 bg-gray-500 text-white hover:bg-gray-600 shadow-sm"
        >
          <Download className="h-4 w-4" />
          Export PDF
        </button>
      </div>
    </div>
  );
};

export default InvoiceCard;